language: ruby
sudo: false
branches:
    only:
        - master
rvm:
    - 2.1.5
install:
    - gem install --no-rdoc --no-ri bundler jekyll rake redcarpet
script:
    - rake publish
env:
    global:
        secure: A4fjJxnXO5rhcyUs2o3IesD7moN66TF7HmGLqjQBCXQHTZeIrfj45EuK3f1d4SnEJXehc5CjaxuSg462/WwGWPI7Ysv/9dbxeHXAIDIZqJa+mMq4GC5XaiBNPWr+i4uRtzyBYz2J2LOj5GIXAZU5TnDXI4Mlju3yH7lq4piQXE0=
