language: ruby
sudo: false
branches:
    only:
        - source
rvm:
    - 2.1.5
install:
    - gem install --no-rdoc --no-ri bundler jekyll rake redcarpet
script:
    - rake publish
global:
    env:
        secure: CLmIVBPw+pXrZ35M8qV400iziu/AWoAAR/cdHZfCteeoGn3LK5Y/lNHK2rJdu92QsBZn0/+MbbYVyPMnHH30tdtKdAV72+ONgnLrVYjmql/1YnxtHcuOzP8nddzMKn3hQhdSvIFswWYD933b7HX+zWcpy0V+8q4eqfwIJ6Cfs3A=
