language: ruby
sudo: false
branches:
  only:
  - master
rvm:
- 2.1.5
install:
- gem install --no-rdoc --no-ri bundler jekyll rake redcarpet
script:
- rake publish
env:
  global:
  - secure: esqa3AMyKwmQUMWpHdOF/KDO9qM3f2gmLj8LivL3n3r47hUqCJMMh/4JNHbiU1KoE7w/UjgOdd0vPqtmlXDyjzI4gNPbUGIwQmKAHC+CMM/vnmhJIYTkvswVbWDvIS1AAJyw9+witqlux+GBMGeeUGWL+FU6LXFzjgYRpuJTB1A=
